# Linking plots

## Why link visualizations 

Most data is _multidimensional_

- Hard to look at more than 3-5 dimensions in a single plot
- Facets/trellis graphs allow us to see multiple views
    - Cannot show which **observations** are aligned across the facets
- We can look at multiple idioms and visualization types for the same data
    - How do the same observations translate with respect to others across different visualizations

Interactive graphs to the rescue

- link observations while looking at multiple viewpoints
- Show related patterns across view points
- Using controls to make simultaneous changes across multiple plots

## Let's start with a scatterplot matrix
:::: {.columns}
::: {.column width="25%"}
### Code
```{{ojs}}
datasets = require('vega-datasets@1')
cars = datasets['cars.json'].url

vl.markCircle()
    .data(cars)
    .encode(
      vl.x().fieldQ(vl.repeat('column')),
      vl.y().fieldQ(vl.repeat('row')),
      vl.color().fieldO('Cylinders'),
    )
    .width(140)
    .height(140)
    .repeat({
      column: ['Acceleration', 'Horsepower', 'Miles_per_Gallon'],
      row: ['Miles_per_Gallon', 'Horsepower', 'Acceleration']
    })
    .render();
```
:::
::: {.column width="75%"}
```{ojs}
//| echo: false
datasets = require('vega-datasets@1')
//cars = datasets['cars.json'].url

vl.markCircle()
    .data(cars)
    .encode(
      vl.x().fieldQ(vl.repeat('column')),
      vl.y().fieldQ(vl.repeat('row')),
      vl.color().fieldO('Cylinders'),
    )
    .width(140)
    .height(140)
    .repeat({
      column: ['Acceleration', 'Horsepower', 'Miles_per_Gallon'],
      row: ['Miles_per_Gallon', 'Horsepower', 'Acceleration']
    })
    .render();
```
:::
::::

We can't tell which observations are actually in which part of each subplot.



## Adding more depth: selecting & linking 

```{ojs}
//| echo: false
 brush = vl.selectInterval()
    .resolve('global'); // resolve all selections to a single global instance
  
 legend = vl.selectPoint()
    .fields('Cylinders')
    .bind('legend'); // bind to interactions with the color legend
  
 brushAndLegend = vl.and(brush, legend);
  
 vl.markCircle()
    .data(cars)
    .params(brush, legend)
    .encode(
      vl.x().fieldQ(vl.repeat('column')),
      vl.y().fieldQ(vl.repeat('row')),
      vl.color().if(brushAndLegend, vl.fieldO('Cylinders')).value('grey'),
      vl.opacity().if(brushAndLegend, vl.value(0.8)).value(0.1)
    )
    .width(140)
    .height(140)
    .repeat({
      column: ['Acceleration', 'Horsepower', 'Miles_per_Gallon'],
      row: ['Miles_per_Gallon', 'Horsepower', 'Acceleration']
    })
    .render();
```

[Code link](https://observablehq.com/d/818210f341a48a61)


## Changing views: linking different idioms

We can look at linking different idioms that are based on the same dataset

```{ojs}
//| echo: false
movies = datasets['movies.json']()
{
  const brush = vl.selectInterval()
    .encodings('x'); // limit selection to x-axis (year) values
  
  // dynamic query histogram
  const years = vl.markBar({width: 4})
    .data(movies)
    .params(brush)
    .encode(
      vl.x().year('Release_Date').title('Films by Release Year'),
      vl.y().count().title(null)
    )
    .width(600)
    .height(50);
  
  // ratings scatter plot
  const ratings = vl.markCircle()
    .data(movies)
    .encode(
      vl.x().fieldQ('Rotten_Tomatoes_Rating').axis({title: "Rotten Tomatoes rating"}),
      vl.y().fieldQ('IMDB_Rating').axis({title: "IMDB rating"}),
      vl.tooltip().fieldN('Title'),
      vl.opacity().if(brush, vl.value(0.75)).value(0.05)
    )
    .width(600)
    .height(400);

  return vl.vconcat(years, ratings).spacing(5).render();
}
```

Here, we can select a range of release years to see if the association between the two ratings changes or not.

:::{.aside}
[Vega-Lite code](https://observablehq.com/d/13718279eb786093)

```{python}
#| code-fold: true
#| eval: false
import pandas as pd
import altair as alt

movies = "https://cdn.jsdelivr.net/npm/vega-datasets@1/data/movies.json"

brush = alt.selection_interval(
    encodings=['x'] # limit selection to x-axis (year) values
)

# dynamic query histogram
years = alt.Chart(movies).mark_bar().add_selection(
    brush
).encode(
    alt.X('year(Release_Date):T', title='Films by Release Year'),
    alt.Y('count():Q', title=None)
).properties(
    width=650,
    height=50
)

# scatter plot, modify opacity based on selection
ratings = alt.Chart(movies).mark_circle().encode(
    x='Rotten_Tomatoes_Rating:Q',
    y='IMDB_Rating:Q',
    tooltip='Title:N',
    opacity=alt.condition(brush, alt.value(0.75), alt.value(0.05))
).properties(
    width=650,
    height=400
)

alt.vconcat(years, ratings).properties(spacing=5)
```
:::

# Adding controls for filtering

## Dynamic queries

A dynamic query:

- represents a query graphically,
- provides visible limits on the query range,
- provides a graphical representation of the data and query result,
- gives immediate feedback of the result after every query adjustment,
- and allows novice users to begin working with little training.

The idea here is to make rapid exploration of the data to identify patterns. 
These can be achieved using tools like sliders, radio buttons, and menus

::: {.aside}
Ahlberg, Williamson & Schneiderman (1992)
:::

## Menus

```{ojs}
//| echo: false
//| cache: false
import {uniqueValid} from '@uwdata/data-utilities'
```

```{ojs}
//| echo: false
//| cache: false
genres = uniqueValid(movies, d => d.Major_Genre)
mpaa = ['G', 'PG', 'PG-13', 'R', 'NC-17', 'Not Rated']

selectGenre = vl.selectPoint("Select")
    .fields("Major_Genre")
    .init({Major_Genre: genres[0]})
    .bind(vl.menu(genres))
    
vl.markCircle()
    .data(movies)
    .params(selectGenre)
    .encode(
      vl.x().fieldQ('Rotten_Tomatoes_Rating'),
      vl.y().fieldQ('IMDB_Rating'),
      vl.tooltip().fieldN('Title'),
      vl.opacity().if(selectGenre, vl.value(0.75)).value(0.05)
    )
    .render();
```

::: {.aside}

[Vega-Lite code](https://observablehq.com/d/9f0a8fd0428ccbfb#cell-11)

```{python}
#| code-fold: true
#| eval: false
df = pd.read_json(movies) # load movies data
genres = df['Major_Genre'].unique() # get unique field values
genres = list(filter(lambda d: d is not None, genres)) # filter out None values
genres.sort()

mpaa = ['G', 'PG', 'PG-13', 'R', 'NC-17', 'Not Rated']

selectGenre = alt.selection_single(
    name='Select', # name the selection 'Select'
    fields=['Major_Genre'], # limit selection to the Major_Genre field
    init={'Major_Genre': genres[0]}, # use first genre entry as initial value
    bind=alt.binding_select(options=genres) # bind to a menu of unique genre values
)

alt.Chart(movies).mark_circle().add_selection(
    selectGenre
).encode(
    x='Rotten_Tomatoes_Rating:Q',
    y='IMDB_Rating:Q',
    tooltip='Title:N',
    opacity=alt.condition(selectGenre, alt.value(0.75), alt.value(0.05))
)
```

:::

## Radio buttons

```{ojs}
//| echo: false

{
  // point-value selection over [Major_Genre, MPAA_Rating] pairs
  // use specific hard-wired values as the initial selected values
  const selection = vl
    .selectPoint("Select")
    .fields("Major_Genre", "MPAA_Rating")
    .init({ Major_Genre: "Drama", MPAA_Rating: "R" })
    .bind({ Major_Genre: vl.menu(genres), MPAA_Rating: vl.radio(mpaa) });

  // scatter plot, modify opacity based on selection
  return vl
    .markCircle()
    .data(movies)
    .params(selection)
    .encode(
      vl.x().fieldQ("Rotten_Tomatoes_Rating"),
      vl.y().fieldQ("IMDB_Rating"),
      vl.tooltip().fieldN("Title"),
      vl.opacity().if(selection, vl.value(0.75)).value(0.05)
    )
    .render();
}
```

::: {.aside}

[Vega-Lite code](https://observablehq.com/d/9f0a8fd0428ccbfb#cell-26)

```{python}
#| code-fold: true
#| eval: false
# single-value selection over [Major_Genre, MPAA_Rating] pairs
# use specific hard-wired values as the initial selected values
selection = alt.selection_single(
    name='Select',
    fields=['Major_Genre', 'MPAA_Rating'],
    init={'Major_Genre': 'Drama', 'MPAA_Rating': 'R'},
    bind={'Major_Genre': alt.binding_select(options=genres), 'MPAA_Rating': alt.binding_radio(options=mpaa)}
)
  
# scatter plot, modify opacity based on selection
alt.Chart(movies).mark_circle().add_selection(
    selection
).encode(
    x='Rotten_Tomatoes_Rating:Q',
    y='IMDB_Rating:Q',
    tooltip='Title:N',
    opacity=alt.condition(selection, alt.value(0.75), alt.value(0.05))
)
```

:::




