---
title: "Minimum standards for deliverables"
date: last-modified
date-format: "dddd MMM D, YYYY [at] hh:mm a"
format: html
---

::: callout-warning
Violation of these guidelines will result in an automatic deduction of 1 grade step
:::

## Code

- Code should be commented as needed to explain what is being done
- Code should be styled using styler/lintr in R
- No warnings or messages should be visible in the final report
- No packages should be installed in the code (You should never include code to install packages in a Quarto document)

## Homework submissions (Quarto documents)

- The code standards above apply
- All code should be visible and not folded, unless otherwise specified
- Any visualizations should be properly annotated, with no variable names visible
- All text should be checked for spelling and grammar and should be in good quality English (Grammarly is a friend here)

### After Homework 5:

- All output should be formatted after Homework 5. **No raw output**. Use the capabilities of R and Quarto to achieve this.
	- In particular,  consider Rich Iannone's work around the **gt** package.
- All plots should be numbered/labeled so they can be referred to in the text and in reviews. All plots should also have self-explanatory captions
- Pages with multiple topical sections should also contain a table of contents, either fixed or floating
- References should be clearly cited and there should be a reference list on the page where the reference is made.
- If you are using code from other sources (e.g., Stack Overflow, GitHub, etc.), you should provide a reference to the source in a comment in the code
- Any use of AI tools (e.g., ChatGPT, Bard, etc.) should be clearly indicated in a comment in the code


## Final reports (PDF, html, etc.)

- All guidelines for homework submissions after Homework 5 apply
- Code should be folded, and not echoed
	- No code should be visible in the final report
- All figures and tables should be numbered and have self-explanatory captions
- There should be a reference list at the end of the document
- Either the raw Quarto file or all the code used to generate the report should be submitted as an appendix to the final report. This should be properly formatted and commented code that can be run to generate the data-drive artufacts (tables, figures, etc.) in the report


