# Moving from Vega to Vega-Lite

## Vega-Lite

Vega-Lite is a _high-level_ grammar of interactive graphics

It uses a declarative JSON syntax to specify visualizations for data analysis and presentation

:::{.fragment}
### Differences with Vega

- Automatically produces components like axes, legends and scales using _carefully designed rules_
- Meant for quick visualization authoring
- Supports _data transformations_ (aggregation, filtering, binning, sorting) and _visual transformations_ (stacking, faceting)
- More concise specification

:::

:::{.fragment}
### Can you still use Vega?

Yes. Vega-Lite :: Vega as seaborn :: matplotlib. You can create graphics quickly and then drop down for more fine control. 

:::

## Using Vega-Lite in ojs

We have to first load the Vega-Lite specification into our environment.

```{ojs}
//| echo: fenced
//| code-fold: false
import {vl} from "@vega/vega-lite-api-v5"
```

```{ojs}
//| echo: false
import {printTable} from '@uwdata/data-utilities'
```

## Data for Vega-Lite

Data is assumed to be a **tidy** data frame with named data _columns_. After importing, it
is stored as an array of JavaScript objects.

As in Vega, you can import data as a URL, or an array of objects

::: {.callout-tip appearance="simple"}
You can play with a variety of standard "book" data available in the [`vega-datasets`](https://github.com/vega/vega-datasets/tree/main/data) repo. These can be accessed in OJS by `data = require('vega-datasets@1')`. You can also access these from Python using `pip install vega_datasets` and then importing the `vega_dataset` library
:::

## Data types

There are four basic data types:

```{r}
#| echo: false
#| eval: true
library(tibble)
library(gt)
tribble(
   ~Type, ~Description,~Function,
   "Nominal (N)", "Categorical data", "`fieldN`",
   "Ordinal (O)", "Ordinal data", "`fieldO`",
   "Quantitative (Q)", "Quantitative data", "`fieldQ`",
   "Temporal (T)", "Temporal data", "`fieldN`"
) |> 
gt() |> fmt_markdown("Function")

```

These are specified in the encoding steps to ensure the right kind of plotting is done.

## Vega-Lite: API vs JSON

::: {.panel-tabset}

## API
```{ojs}
exdat = data['cars.json']()
vl.markCircle()
   .params(vl.selectInterval().bind('scales'))
   .encode(
   vl.x().fieldQ('Horsepower').scale({'domain': [75, 150]}),
   vl.y().fieldQ("Miles_per_Gallon").scale({'domain': [20,40]}),
   vl.size().fieldQ("Cylinders"),
)
.data(exdat).render()
```

## JSON
```{ojs}
embed({
  "$schema":"https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"values": exdat},
  "mark": "circle",
  "params": [
    {
      "name": "name4",
      "bind": "scales",
      "select": {"type": "interval"}
    }
  ],
  "encoding": {
    "x": {
      "field":"Horsepower", "type": "quantitative",
      "scale": {"domain": [75,150]}
    },
    "y": {
      "field": "Miles_per_Gallon", "type": "quantitative",
      "scale": {"domain": [20,40]}
    },
    "size": {
      "field": "Cylinders", "type":"quantitative"
    }
  }
})
embed = require('vega-embed')
```

:::

Typically we prefer the API rather than the JSON


## Seattle temperatures

```{ojs}
data = require('vega-datasets@1')
seattle_temps = data['seattle-weather.csv']()
Inputs.table(seattle_temps.slice(0,5), {
  header: {
    date: "Date",
    precipitation: "Precipitation",
    temp_max: "Max Temperature",
    temp_min: "Min Temperature",
    wind: "Wind",
    weather: "Weather"
}})
```
```{ojs}
//| output-location: column
//| code-fold: false
//| code-line-numbers: "|4,6"
vl.markPoint()
   .data(seattle_temps)
   .encode(
      vl.x().fieldT('date')
         .axis({title: "Date", format: "%b %Y"}),
      vl.y().fieldQ('temp_max')
         .axis({title: "Maximum temperature (C)"})
   ) 
   .render()
```

## Aggregation

```{ojs}
//| output-location: column
//| code-fold: false
vl.markPoint()
   .data(seattle_temps)
   .encode(
      vl.x().month('date')
         .axis({title: "Month", format: "%b"}), 
      vl.y().mean('temp_max')
         .scale({domain: [-5,40]})
         .axis({title: "Average Maximum Daily Temperature (C)"})
   )
   .render()
```

- `month` extracts the month from the date
- `mean` computes the average by month

## Layering

```{ojs}
//| code-fold: false
//| output-location: column

line1= vl.markLine({color: "red"})
   .data(seattle_temps)
   .encode(
      vl.x().month('date'),
      vl.y().mean('temp_max')
   )

points1= vl.markCircle()
   .data(seattle_temps)
   .encode(
      vl.x().month('date').axis({title: "Month", format: "%b"}),
      vl.y().fieldQ('temp_max').axis({title:"Maximum temperature"})
   )
   
 vl.layer(line1, points1).render()
```

## A bit more complex

:::: {.columns}
::: {.columns width="50%"}

```{{ojs}}
//| output-location: column
//| code-fold: false
plot1 = vl.markPoint({filled: true})
   .encode(
      vl.color().fieldN("weather").title("Weather"),
      vl.size().fieldQ("precipitation").scale({domain: [-1,50], range:[10,500]}).title("Precipitation"),
      vl.order().fieldQ("precipitation").sort("descending"),
      vl.x().timeMD("date").axis({title: "Date", format: "%b"}),
      vl.y().fieldQ("temp_max").scale({domain: [-5,40]}).axis({title:"Max Daily Temp (C)"})
)
   .width(800)

plot2 = vl.markBar()
   .encode(
      vl.color().title("Weather"),
      vl.x().count(),
      vl.y().fieldN("weather").title("Weather")
).width(800)

vl.vconcat(plot1, plot2)
   .data(seattle_temps)
   .autosize({type:'fit-x', contains: 'padding'})
   .render()
```
:::
::: {.column width="50%"}

```{ojs}
//| echo: false
plot1 = vl.markPoint({filled: true})
   .encode(
      vl.color().fieldN("weather").title("Weather"),
      vl.size().fieldQ("precipitation").scale({domain: [-1,50], range:[10,500]}).title("Precipitation"),
      vl.order().fieldQ("precipitation").sort("descending"),
      vl.x().timeMD("date").axis({title: "Date", format: "%b"}),
      vl.y().fieldQ("temp_max").scale({domain: [-5,40]}).axis({title:"Max Daily Temp (C)"})
)
   .width(800)

plot2 = vl.markBar()
   .encode(
      vl.color().title("Weather"),
      vl.x().count(),
      vl.y().fieldN("weather").title("Weather")
).width(800)

vl.vconcat(plot1, plot2)
   .data(seattle_temps)
   .autosize({type:'fit-x', contains: 'padding'})
   .render()
```
:::
::::

## Interaction: brushing 

```{ojs}
//| code-fold: true
brush1 = vl.selectInterval().encodings('x')
click1 = vl.selectPoint().encodings('color')

plot11 = vl.markPoint({filled: true})
   .encode(
      vl.color().value('lightgray')
         .if(brush1, vl.color().fieldN('weather').title("Weather")),
      vl.size().fieldQ("precipitation").scale({domain: [-1,50], range:[10,500]}).title("Precipitation"),
      vl.order().fieldQ("precipitation").sort("descending"),
      vl.x().timeMD("date").axis({title: "Date", format: "%b"}),
      vl.y().fieldQ("temp_max").scale({domain: [-5,40]}).axis({title:"Max Daily Temp (C)"})
)
   .width(800)
   .height(300)
   .params(brush1)
   .transform(vl.filter(click1))

plot21 = vl.markBar()
   .encode(
      vl.color().if(click1, vl.color().fieldN('weather')).value('lightgray').title("Weather"),
      vl.x().count(),
      vl.y().fieldN("weather").title("Weather")
).width(800)
.params(click1)
.transform(vl.filter(brush1))

vl.vconcat(plot11, plot21)
   .data(seattle_temps)
   .autosize({type:'fit-x', contains: 'padding'})
   .render()
```

## Vega-Lite: Slider

```{ojs}
cars = data['cars.json']()
isOrigin = vl.selectPoint('isOrigin')
   .fields("Origin")
   .bind('legend') // bind to legend interactions
   
isYear = vl.selectPoint('isYear')
   .fields('Year').value(1970)
   .bind(vl.slider(1970, 1980, 1).name("Year"))

show=vl.and(isOrigin, isYear)

vl.markCircle()
   .data(cars)
   .transform(
   vl.calculate('year(datum.Year)').as("Year")
).params(isOrigin, isYear)
.encode(
   vl.x().fieldQ("Horsepower"),
   vl.y().fieldQ('Miles_per_Gallon'),
   vl.color().if(show, vl.color().fieldN('Origin')).value('grey'),
   vl.opacity().if(show, vl.value(1.0)).value(0.2)
).render()
```

## Layers

```{ojs}
weather = data['weather.csv']()
Inputs.table(weather.slice(0,5))
//printTable(weather.slice(0,5))
vl.markArea({opacity: 0.3})
   .data(weather)
   .encode(
vl.x().month('date').axis({title: "Month"}),
vl.y().average('temp_max').axis({title: "Max temperature"}),
vl.y2().average('temp_min').title( "Min temperature"),
      vl.color().fieldN('location').title("Location")
).render()
```

## Facets

```{ojs}
//| code-line-numbers: "8"
vl.markBar()
   .data(weather)
   .transform(vl.filter('datum.location=="Seattle"'))
   .encode(
    vl.x().fieldQ('temp_max').bin(true).title('Temperature (°C)'),
      vl.y().count(),
      vl.color().fieldN('weather'),
      vl.column().fieldN('weather')
).width(150)
.height(150)
.render();
```

## Concatenating graphs


```{ojs}
base = vl.markLine()
    .data(weather)
    .encode(
      vl.x().month('date').title(null),
      vl.color().fieldN('location')
    )
    .width(240)
    .height(180);

temp = base.encode(vl.y().average('temp_max'));
 precip = base.encode(vl.y().average('precipitation'));
wind = base.encode(vl.y().average('wind'));

vl.hconcat(temp, precip, wind).render();

```

::: {.notes}
Note that we're encoding just the x variable in `base`, and can add the encoding for the y later.
:::

## Vega-Lite and Altair

We've been looking at the Vega-Lite Javascript API, rather than the JSON specification. 

This is very similar to what we will see in Altair

