import os
import shutil
import sys

# generated by chatgpt
# to call script: python script_name.py subdirectory1 subdirectory2 ...


# Function to remove the 'img' subdirectory within the given directory
def remove_img_directory(directory):
    img_directory = os.path.join(directory, "img")
    if os.path.isdir(img_directory):
        shutil.rmtree(img_directory)
        print(f"Removed 'img' subdirectory from {directory}.")
    else:
        print(f"'img' subdirectory does not exist in {directory}.")


# Get the subdirectory names from command-line arguments
if len(sys.argv) < 2:
    print("Please provide at least one subdirectory name as a command-line argument.")
    sys.exit(1)

subdirectories = sys.argv[1:]

# Remove the 'img' subdirectory from each subdirectory
for subdirectory in subdirectories:
    remove_img_directory(subdirectory)
